import FilterDropdown from "./filterDropdown";
import RangeSlider from "./rangeSlider";

function Filter() {


    const sector = [
        { id: 1, info: "Economy" },
        { id: 2, info: "Army" },
        { id: 3, info: "Index" },
        { id: 4, info: "Transportation" },
        { id: 5, info: "Social" },
        { id: 6, info: "Government" },
        { id: 7, info: "Business" },
        { id: 8, info: "Technology & Innovation" },
        { id: 9, info: "Agriculture" },
    ]



    const subSector = [
        { id: 1, info: "Banking system access and deph" },
        { id: 2, info: "Energy and environment" },
        { id: 3, info: "Financial Sector and Development" },
        { id: 4, info: "Money" },
        { id: 5, info: "Consumption and Invensment" },
        { id: 6, info: "Industry Oil coal and electricity" },
        { id: 7, info: "Forecast from the IMF" },
        { id: 8, info: "Productivity and Labor Market" },
        { id: 9, info: "Electricity" },
        { id: 11, info: "International trade and Invensment " },
        { id: 12, info: "Economic Structure" },
        { id: 13, info: "Government" },
        { id: 14, info: "Tourism" },
        { id: 15, info: "Minerals" },
        { id: 16, info: "Stock market, insurance, pensions " },
        { id: 17, info: "Shares of world totals " },

    ]


    const indicator = [
        { id: 1, info: "Electricity consumption billion kilowatthours" },
        { id: 2, info: "Electricity exports billion kilowatthours" },
        { id: 3, info: "Electricity imports billion kilowatthours" },
        { id: 4, info: "Electricity production billion kilowatthours" },
        { id: 5, info: "Electricity production capacity million kilowatts" },
        { id: 6, info: "Fossil fuels electricity capacity million kilowatts " },
        { id: 7, info: "Fossil fuels electricity generetion billion kilowatthours" },
        { id: 8, info: "Geotheromal electricity capacity million kilowatts" },
        { id: 9, info: "Geotheromal electricity generation billion kilowatthours" },
        { id: 10, info: "Hydroelectricity capacity million kilowatts" },
        { id: 11, info: "Hydroelectricity generation billion kilowatthours" },
        { id: 12, info: "Nuclear electricity capacity million kilowatts " },
        { id: 13, info: "Solar electricity capacity million kilowatts" },
        { id: 14, info: "Solar electricity generation billion kilowatthours" },
        { id: 15, info: "Wind electricity capacity million kilowatts" },
        { id: 16, info: "Wind electricit generation billion kilowatthours" },
    ]

    const countries = [
        { id: 1, info: "Afghanistan" },
        { id: 2, info: "Albania" },
        { id: 3, info: "Algeria" },
        { id: 4, info: "Andorra" },
        { id: 5, info: "Angola" },
        { id: 6, info: "Antigua and Barbuda" },
        { id: 7, info: "Argentina" },
        { id: 8, info: "Armenia" },
        { id: 9, info: "Australia" },
        { id: 10, info: "Austria" },
        { id: 11, info: "Azerbaijan" },
        { id: 12, info: "Bahamas" },
        { id: 13, info: "Bahrain" },
        { id: 14, info: "Bangladesh" },
        { id: 15, info: "Barbados" },
        { id: 16, info: "Belarus" },
        { id: 17, info: "Belgium" },
        { id: 18, info: "Belize" },
        { id: 19, info: "Benin" },
        { id: 20, info: "Bhutan" },
        { id: 21, info: "Bolivia" },
        { id: 22, info: "Bosnia and Herzegovina" },
        { id: 23, info: "Botswana" },
        { id: 24, info: "Brazil" },
        { id: 25, info: "Brunei" },
        { id: 26, info: "Bulgaria" },
        { id: 27, info: "Burkina Faso" },
        { id: 28, info: "Burundi" },
        { id: 29, info: "Cabo Verde" },
        { id: 30, info: "Cambodia" },
        { id: 31, info: "Cameroon" },
        { id: 32, info: "Canada" },
        { id: 33, info: "Central African Republic" },
        { id: 34, info: "Chad" },
        { id: 35, info: "Chile" },
        { id: 36, info: "China" },
        { id: 37, info: "Colombia" },
        { id: 38, info: "Comoros" },
        { id: 39, info: "Congo (Congo-Brazzaville)" },
        { id: 40, info: "Costa Rica" },
        { id: 41, info: "Croatia" },
        { id: 42, info: "Cuba" },
        { id: 43, info: "Cyprus" },
        { id: 44, info: "Czechia (Czech Republic)" },
        { id: 45, info: "Denmark" },
        { id: 46, info: "Djibouti" },
        { id: 47, info: "Dominica" },
        { id: 48, info: "Dominican Republic" },
        { id: 49, info: "Ecuador" },
        { id: 50, info: "Egypt" },
        { id: 51, info: "El Salvador" },
        { id: 52, info: "Equatorial Guinea" },
        { id: 53, info: "Eritrea" },
        { id: 54, info: "Estonia" },
        { id: 55, info: "Eswatini (fmr. Swaziland)" },
        { id: 56, info: "Ethiopia" },
        { id: 57, info: "Fiji" },
        { id: 58, info: "Finland" },
        { id: 59, info: "France" },
        { id: 60, info: "Gabon" },
        { id: 61, info: "Gambia" },
        { id: 62, info: "Georgia" },
        { id: 63, info: "Germany" },
        { id: 64, info: "Ghana" },
        { id: 65, info: "Greece" },
        { id: 66, info: "Grenada" },
        { id: 67, info: "Guatemala" },
        { id: 68, info: "Guinea" },
        { id: 69, info: "Guinea-Bissau" },
        { id: 70, info: "Guyana" },
        { id: 71, info: "Haiti" },
        { id: 72, info: "Holy See" },
        { id: 73, info: "Honduras" },
        { id: 74, info: "Hungary" },
        { id: 75, info: "Iceland" },
        { id: 76, info: "India" },
        { id: 77, info: "Indonesia" },
        { id: 78, info: "Iran" },
        { id: 79, info: "Iraq" },
        { id: 80, info: "Ireland" },
        { id: 81, info: "Israel" },
        { id: 82, info: "Italy" },
        { id: 83, info: "Jamaica" },
        { id: 84, info: "Japan" },
        { id: 85, info: "Jordan" },
        { id: 86, info: "Kazakhstan" },
        { id: 87, info: "Kenya" },
        { id: 88, info: "Kiribati" },
        { id: 89, info: "Korea (North)" },
        { id: 90, info: "Korea (South)" },
        { id: 91, info: "Kosovo" },
        { id: 92, info: "Kuwait" },
        { id: 93, info: "Kyrgyzstan" },
        { id: 94, info: "Laos" },
        { id: 95, info: "Latvia" },
        { id: 96, info: "Lebanon" },
        { id: 97, info: "Lesotho" },
        { id: 98, info: "Liberia" },
        { id: 99, info: "Libya" },
        { id: 100, info: "Liechtenstein" },
    ];

    const years = [
        { id: 1, info: "1980" },
        { id: 2, info: "1981" },
        { id: 3, info: "1982" },
        { id: 4, info: "1983" },
        { id: 5, info: "1984" },
        { id: 6, info: "1985" },
        { id: 7, info: "1986" },
        { id: 8, info: "1987" },
        { id: 9, info: "1988" },
        { id: 10, info: "1989" },
        { id: 11, info: "1990" },
        { id: 12, info: "1991" },
        { id: 13, info: "1992" },
        { id: 14, info: "1993" },
        { id: 15, info: "1994" },
        { id: 16, info: "1995" },
        { id: 17, info: "1996" },
        { id: 18, info: "1997" },
        { id: 19, info: "1998" },
        { id: 20, info: "1999" },
        { id: 21, info: "2000" },
        { id: 22, info: "2001" },
        { id: 23, info: "2002" },
        { id: 24, info: "2003" },
        { id: 25, info: "2004" },
        { id: 26, info: "2005" },
        { id: 27, info: "2006" },
        { id: 28, info: "2007" },
        { id: 29, info: "2008" },
        { id: 30, info: "2009" },
        { id: 31, info: "2010" },
        { id: 32, info: "2011" },
        { id: 33, info: "2012" },
        { id: 34, info: "2013" },
        { id: 35, info: "2014" },
        { id: 36, info: "2015" },
        { id: 37, info: "2016" },
        { id: 38, info: "2017" },
        { id: 39, info: "2018" },
        { id: 40, info: "2019" },
        { id: 41, info: "2020" },
        { id: 42, info: "2021" },
        { id: 44, info: "2023" },
        { id: 45, info: "2024" },
        { id: 46, info: "2025" },
    ]

    return (
   <div className="flex px-2 py-2 ">
 <div className="flex justify-center  gap-[10px]">
            <FilterDropdown name="Sector" items={sector} />
            <FilterDropdown name="Subsector" items={subSector} />
            <FilterDropdown name="Indicator" items={indicator} />
            <FilterDropdown name="Country" items={countries} />
            <FilterDropdown name="Year" items={years} />
        </div>
        <RangeSlider />

   </div>

       
    )
}

export default Filter;